

TEAMS = {'TAMPA BAY RAYS':'TBA',
 'MIAMI MARLINS':'MIA',
 'BOSTON RED SOX':'BOS',
 'LOS ANGELES ANGELS':'ANA',
 'OAKLAND ATHLETICS':'OAK',
 'TORONTO BLUE JAYS':'TOR',
 'TEXAS RANGERS':'TEX',
 'NEW YORK YANKEES':'NYA',
 'CHICAGO WHITE SOX':'CHA',
 'BALTIMORE ORIOLES':'BAL',
 'DETROIT TIGERS':'DET',
 'PHILADELPHIA PHILLIES':'PHI',
 'MILWAUKEE BREWERS':'MIL',
 'LOS ANGELES DODGERS':'LAN',
 'CINCINNATI REDS':'CIN',
 'CHICAGO CUBS':'CHN',
 'COLORADO ROCKIES':'COL',
 'CLEVELAND INDIANS':'CLE',
 'ST. LOUIS CARDINALS':'SLN',
 'KANSAS CITY ROYALS':'KCA',
 'MINNESOTA TWINS':'MIN',
 'SEATTLE MARINERS':'SEA',
 'SAN FRANCISCO GIANTS':'SFN',
 "ARIZONA D'BACKS":'ARI',
 'SAN DIEGO PADRES':'SDN',
 'WASHINGTON NATIONALS':'WAS',
 'PITTSBURGH PIRATES':'PIT',
 'NEW YORK METS':'NYN',
 'HOUSTON ASTROS':'HOU',
 'ATLANTA BRAVES':'ATL'}

LEAGUE = {'TBA':'AL',
         'MIA':'NL',
         'BOS':'AL',
         'ANA':'AL',
         'OAK':'AL',
         'TOR':'AL',
         'TEX':'AL',
         'NYA':'AL',
         'CHA':'AL',
         'BAL':'AL',
         'DET':'AL',
         'PHI':'NL',
         'MIL':'NL',
         'LAN':'NL',
         'CIN':'NL',
         'CHN':'NL',
         'COL':'NL',
         'CLE':'AL',
         'SLN':'NL',
         'KCA':'AL',
         'MIN':'AL',
         'SEA':'AL',
         'SFN':'NL',
         'ARI':'NL',
         'SDN':'NL',
         'WAS':'NL',
         'PIT':'NL',
         'NYN':'NL',
         'HOU':'AL',
         'ATL':'NL'}


TEAM_INITIALS = {'TBA':'TB',
                 'MIA':'MIA',
                 'BOS':'BOS',
                 'ANA':'LAA',
                 'OAK':'OAK',
                 'TOR':'TOR',
                 'TEX':'TEX',
                 'NYA':'NYY',
                 'CHA':'CHW',
                 'BAL':'BAL',
                 'DET':'DET',
                 'PHI':'PHI',
                 'MIL':'MIL',
                 'LAN':'LAD',
                 'CIN':'CIN',
                 'CHN':'CHC',
                 'COL':'COL',
                 'CLE':'CLE',
                 'SLN':'STL',
                 'KCA':'KC',
                 'MIN':'MIN',
                 'SEA':'SEA',
                 'SFN':'SF',
                 'ARI':'ARI',
                 'SDN':'SD',
                 'WAS':'WAS',
                 'PIT':'PIT',
                 'NYN':'NYM',
                 'HOU':'HOU',
                 'ATL':'ATL'}

TEAM_INIT = {'ARI':'ARI',
'SD':'',
'TEX':'',
'TB':'',
'MIN':'',
'NYY':'',
'PHI':'',
'TOR':'',
'BOS':'',
'OAK':'',
'NYM':'',
'LAA':'',
'CIN':'',
'CLE':'',
'SF':'',
'STL':'',
'CHW':'',
'MIL':'',
'CHC':'',
'BAL':'',
'MIA':'',
'PIT':'',
'HOU':'',
'COL':'',
'SEA':'',
'WAS':'',
'LAD':'',
'DET':'',
'ATL':'',
'KC':'',
'CWS':''}


PLAYERS = {
'JONATHAN GRAY': 'JON GRAY',
'C.C. SABATHIA': 'CC SABATHIA',
'MATTHEW ANDRIESE': 'MATT ANDRIESE',
'SHOHEI OHTANI': 'SHOHEI (H) OHTANI',
'A.J. POLLOCK': 'AJ POLLOCK',
'DANIEL VOGELBACH': 'DAN VOGELBACH',
'JONATHAN GRAY': 'JON GRAY',
'J.T. REALMUTO': 'JT REALMUTO',
'JACOB MARISNICK': 'JAKE MARISNICK',
'JOSEPH WENDLE': 'JOEY WENDLE',
'MICHAEL MARJAMA' : 'MIKE MARJAMA',
'MICHAEL TAUCHMAN' : 'MIKE TAUCHMAN',
'PATRICK VALAIKA': 'PAT VALAIKA',
'THOMAS PHAM': 'TOMMY PHAM',
'JACOB FARIA' : 'JAKE FARIA',
'JAKOB JUNIS' : 'JAKE JUNIS',
'JAMIE GARCIA' : 'JAIME GARCIA',
'MICHAEL SOROKA' : 'MIKE SOROKA',
'MATTHEW KOCH' : 'MATT KOCH',
'SAMUEL GAVIGLIO' : 'SAM GAVIGLIO',
'MICHAEL MONTGOMERY' : 'MIKE MONTGOMERY',
'MICHAEL FULMER' : 'MIKE FULMER',
'NICHOLAS TROPEANO' : 'NICK TROPEANO',
'ALEXANDER REYES' : 'ALEX REYES',
'CHASE DE JONG' : 'CHASE DEJONG',
'JOSHUA JAMES' : 'JOSH JAMES',
'MATTHEW FESTA' : 'MATT FESTA',
'CHASE DE JONG' : 'CHASE DEJONG'
}

PLAYER_TEAM = {
'JUAN SOTO' : 'WAS',
'JEFF MCNEIL' : 'NYN',
'ADALBERTO MONDESI' : 'KCA',
'JOSHUA RIDDLE' : 'MIA',
'NICK MARTINI' : 'OAK',
'ERIK KRATZ' : 'MIL',
'DAVID FLETCHER' : 'ANA',
'WILLIANS ASTUDILLO' : 'MIN',
"RYAN O'HEARN" : 'KCA',
'MELKY CABRERA' : 'CLE',
'FRANMIL REYES' : 'SDN',
'D.J. STEWART' : 'BAL',
'PABLO REYES' : 'PIT',
"PETER O'BRIEN" : 'MIA',
'BRANDON LOWE' : 'TBA',
'CURTIS CASALI' : 'CIN',
'STEVEN DUGGAR' : 'SFN',
'PATRICK WISDOM' : 'SLN',
'CHRIS HERRMANN' : 'SEA',
'GARRETT HAMPSON' : 'COL',
'JOSE BRICENO' : 'ANA',
'PHIL ERVIN' : 'CIN',
'MARK REYNOLDS' : 'WAS',
'MATT HOLLIDAY' : 'COL',
'CHRISTIN STEWART' : 'DET',
'ISAAC GALLOWAY' : 'MIA',
'AUSTIN DEAN' : 'MIA',
'RYAN LAVARNWAY' : 'PIT',
'MYLES STRAW' : 'HOU',
'KOLBY ALLARD' : 'ATL',
'VIDAL NUNO' : 'TBA',
'ANDREW VELAZQUEZ' : 'TBA',
'TIM FEDEROWICZ' : 'CIN',
'JEFF BRIGHAM' : 'MIA',
'BRANDON PHILLIPS' : 'BOS',
'DECK MCGUIRE' : 'TOR',
'ENYEL DE LOS SANTOS' : 'PHI',
'PETE KOZMA' : 'DET',
'DAKOTA HUDSON' : 'SLN',
'TREVOR PLOUFFE' : 'PHI',
'JUSTIN MILLER' : 'WAS',
'LUIS URIAS' : 'SDN',
'DUSTIN GARNEAU' : 'CHA',
'BEAU TAYLOR' : 'OAK',
'MATT STRAHM' : 'SDN',
'DANIEL PONCEDELEON' : 'SLN',
'CHAD SOBOTKA' : 'ATL',
'BRANDON BARNES' : 'CLE',
'WILMER FONT' : 'LAN',
'ADAM ROSALES' : 'CLE',
'P.J. CONLON' : 'NYN',
'PATRICK KIVLEHAN' : 'ARI',
'DARNELL SWEENEY' : 'TOR',
'TIMOTHY PETERSON' : 'NYN',
'SAMUEL GAVIGLIO' : 'TOR',
'JONATHON BERTI' : 'TOR',
'CORBIN BURNES' : 'MIL',
'HAROLD CASTRO' : 'DET',
'MATT SKOLE' : 'CHA',
'KRIS NEGRON' : 'ARI',
'TANNER ANDERSON' : 'PIT',
'ALEX COLOME' : 'SEA',
'ALLEN WEBSTER' : 'CHN',
'ANTHONY BASS' : 'CHN',
'AUSTEN WILLIAMS' : 'WAS',
'BOBBY WAHL' : 'NYN',
'C.D. PELHAM' : 'TEX',
'CHANCE ADAMS' : 'NYA',
'D.J. JOHNSON' : 'COL',
'DANIEL ZAMORA' : 'NYN',
'DREW SMITH' : 'NYN',
'ERIC HANHOLD' : 'NYN',
'ERIK GOEDDEL' : 'LAN',
'EVAN MARSHALL' : 'CLE',
'EVAN PHILLIPS' : 'ATL',
'JAKE NEWBERRY' : 'KCA',
'JASON ADAM' : 'KCA',
'JEFFREY SPRINGS' : 'TEX',
'JEREMY BLEICH' : 'OAK',
'JERRY VASTO' : 'COL',
'JOHN BARBATO' : 'DET',
'JOSE FERNANDEZ' : 'TOR',
'JOSE VALDEZ' : 'SFN',
'JOSEPH KREHBIEL' : 'ARI',
'KEONE KELA' : 'PIT',
'KYLE WRIGHT' : 'ATL',
'LOUIS COLEMAN' : 'DET',
'MATT BELISLE' : 'MIN',
'MATT HALL' : 'DET',
'MATTHEW FESTA' : 'SEA',
'MIKE ZAGURSKI' : 'MIL',
'MURPHY SMITH' : 'TOR',
'OLIVER PEREZ' : 'CLE',
'PAT VENDITTE' : 'LAN',
'PRESTON GUILMET' : 'SLN',
'ROBERT STOCK' : 'SDN',
'ROBERTO OSUNA' : 'HOU',
'RYAN BRASIER' : 'BOS',
'RYAN MEISINGER' : 'BAL',
'SCOTT COPELAND' : 'NYN',
'TAYLOR COLE' : 'ANA',
'TIM COLLINS' : 'WAS',
'TONY RENDA' : 'BOS',
'TREY WINGENTER' : 'SDN',
'TY BUTTREY' : 'ANA',
'TYLER KINLEY' : 'MIA',
'WILLIAM CUEVAS' : 'BOS',
'WILLIAMS JEREZ' : 'ANA',
'XAVIER CEDENO' : 'CHA',
'YOAN LOPEZ' : 'ARI',
'ZAC ROSSCUP' : 'LAN',
'TERRANCE GORE' : 'CHN',
'DUANE UNDERWOOD' : 'CHN',
'ABIATAL AVELINO' : 'SFN',
'BEN MEYER' : 'MIA',
'JAKE PETRICKA' : 'TOR',
'DREW RUCINSKI' : 'MIA',
'EDWIN JACKSON' : 'OAK',
'WES PARSONS' : 'ATL',
'KYLE MCGOWIN' : 'WAS',
'BRYSE WILSON' : 'ATL',
'ALEX MCRAE' : 'PIT',
'SEAN REID-FOLEY' : 'TOR',
'JOHN ANDREOLI' : 'SEA',
'JUSTIN HANCOCK' : 'CHN',
'MICHAEL REED' : 'ATL',
'CALEB FERGUSON' : 'LAN',
'JOE HUDSON' : 'ANA',
'NEIL RAMIREZ' : 'CLE',
'TOUKI TOUSSAINT' : 'ATL',
'MIKE SOROKA' : 'ATL',
'STEVEN BARON' : 'SLN',
'JUNG-HO KANG' : 'PIT',
'CLAY BUCHHOLZ' : 'ARI',
'NICK FRANKLIN' : 'MIL',
'ROCKY GALE' : 'LAN',
'DUSTIN PETERSON' : 'ATL',
'CASEY KELLY' : 'SFN',
'ADAM MOORE' : 'TBA',
'JACK REINHEIMER' : 'NYN',
'JONATHAN DAVIS' : 'TOR',
'KEVIN KACZMARSKI' : 'NYN',
'JALEN BEEKS' : 'TBA',
'TOMMY MILONE' : 'WAS',
'JAMES NORWOOD' : 'CHN',
'JACOB NIX' : 'SDN',
'BOBBY WILSON' : 'MIN',
'SHANE BIEBER' : 'CLE',
'GABRIEL GUERRERO' : 'CIN',
'DAN BUTLER' : 'BOS',
'MASON WILLIAMS' : 'CIN',
'NICK CIUFFO' : 'TBA',
'JARROD SALTALAMACCHIA' : 'DET',
'AUSTIN DAVIS' : 'PHI',
'MICHAEL PEREZ' : 'TBA',
'DERECK RODRIGUEZ' : 'SFN',
'MITCH WALDING' : 'PHI',
"CHASE D'ARNAUD" : "SFN",
'BRETT KENNEDY' : 'SDN',
'CORBAN JOSEPH' : 'BAL',
'NATHAN ORF' : 'MIL',
'TY KELLY' : 'NYN',
'CEDRIC MULLINS' : 'BAL',
'RAFAEL ORTEGA' : 'MIA',
'SHERMAN JOHNSON' : 'ANA',
'MATT DEN DEKKER' : 'NYN',
'FRANCISCO ARCIA' : 'ANA',
'GIOVANNY URSHELA' : 'TOR',
'STEPHEN WILKERSON' : 'BAL',
'JOSE ADOLIS GARCIA' : 'SLN',
'TONY CRUZ' : 'CIN',
'CHRIS SHAW' : 'SFN',
'KEVIN KRAMER' : 'PIT',
'MIKE TAUCHMAN' : 'COL',
'ERIC YOUNG' : 'ANA',
'KEVIN NEWMAN' : 'PIT',
'TAYLOR WARD' : 'ANA',
'KYLE TUCKER' : 'HOU',
'BRANDON DIXON' : 'CIN',
'RONNY RODRIGUEZ' : 'DET',
'MICHAEL SOROKA' : 'ATL',
'CHRIS VOLSTAD' : 'CHA'
}

#PHIL ERVIN CIN : hand?
#CURTIS CASALI CIN : hand?
#BRANDON DIXON CIN : hand?

ADD_PLAYERS = [
    ['DANIEL WINKLER', 'ATL', 'NL', 'P', 'R', 'R', 'DANIEL WINKLER ATL'],
    ['JESSE BIDDLE', 'ATL', 'NL',  'P', 'L', 'L', 'JESSE BIDDLE ATL'],
    ['SHANE CARLE', 'ATL', 'NL',  'P', 'R', 'R', 'SHANE CARLE ATL'],
    ['JOSHUA JAMES', 'HOU', 'AL',  'P', 'R', 'R', 'JOSHUA JAMES HOU'],
    ['JOSHUA LUCAS', 'BAL', 'AL', 'P', 'R', 'R', 'JOSHUA LUCAS BAL']
    ]


TEAMS = {'TAMPA BAY RAYS':'TBA',
 'MIAMI MARLINS':'MIA',
 'BOSTON RED SOX':'BOS',
 'LOS ANGELES ANGELS':'ANA',
 'OAKLAND ATHLETICS':'OAK',
 'TORONTO BLUE JAYS':'TOR',
 'TEXAS RANGERS':'TEX',
 'NEW YORK YANKEES':'NYA',
 'CHICAGO WHITE SOX':'CHA',
 'BALTIMORE ORIOLES':'BAL',
 'DETROIT TIGERS':'DET',
 'PHILADELPHIA PHILLIES':'PHI',
 'MILWAUKEE BREWERS':'MIL',
 'LOS ANGELES DODGERS':'LAN',
 'CINCINNATI REDS':'CIN',
 'CHICAGO CUBS':'CHN',
 'COLORADO ROCKIES':'COL',
 'CLEVELAND INDIANS':'CLE',
 'ST. LOUIS CARDINALS':'SLN',
 'KANSAS CITY ROYALS':'KCA',
 'MINNESOTA TWINS':'MIN',
 'SEATTLE MARINERS':'SEA',
 'SAN FRANCISCO GIANTS':'SFN',
 "ARIZONA D'BACKS":'ARI',
 'SAN DIEGO PADRES':'SDN',
 'WASHINGTON NATIONALS':'WAS',
 'PITTSBURGH PIRATES':'PIT',
 'NEW YORK METS':'NYN',
 'HOUSTON ASTROS':'HOU',
 'ATLANTA BRAVES':'ATL'}

TEAMS_SHORT = {
'Indians': 'CLE',
'Yankees': 'NYA',
'Red Sox': 'BOS',
'Dodgers': 'LAN',
'Angels': 'ANA',
'Astros': 'HOU',
'Rays': 'TBA',
'Cardinals': 'SLN',
'Rockies': 'COL',
'Diamondbacks': 'ARI',
'Blue Jays': 'TOR',
'Giants': 'SFN',
'Cubs': 'CHN',
'Brewers': 'MIL',
'Royals': 'KCA',
'Phillies': 'PHI',
'Nationals': 'WAS',
'Pirates': 'PIT',
'Marlins': 'MIA',
'Mariners': 'SEA',
'Braves': 'ATL',
'Athletics': 'OAK',
'Twins': 'MIN',
'Orioles': 'BAL',
'Mets': 'NYN',
'Rangers': 'TEX',
'White Sox': 'CHA',
'Reds': 'CIN',
'Padres': 'SDN',
'Tigers': 'DET',
    }
    
    
pit_side_col_list = ['NAME',
 'HAND_pit',
 'G_SIDE_pit',
 'PA_SIDE_pit',
 'AB_SIDE_pit',
 'H_SIDE_pit',
 '1B_SIDE_pit',
 '2B_SIDE_pit',
 '3B_SIDE_pit',
 'HR_SIDE_pit',
 'TB_SIDE_pit',
 'SO_SIDE_pit',
 'BB_SIDE_pit',
 'HBP_SIDE_pit',
 'SF_SIDE_pit',
 'SH_SIDE_pit',
 'DP_SIDE_pit',
 'FB%_SIDE_pit',
 'GB%_SIDE_pit',
 'LD%_SIDE_pit',
 'POP%_SIDE_pit',
 'ISO_SIDE_pit',
 'AVG_SIDE_pit',
 'OBP_SIDE_pit',
 'SLG_SIDE_pit',
 'TAV_SIDE_pit',
 'DRA_SIDE_pit',
 'DRA-_SIDE_pit',
 'CFIP_SIDE_pit',
 'BASES_VS_AB_pit']


features_top_list = ['BASES_VS_AB_pit',
 'SLG_SIDE_pit',
 'AVG_batter',
 'def_LD%',
 'hit_mult',
 'SLG_batter',
 'pitcher_DRA',
 'DRA_SIDE_pit',
 'pitcher_FIP',
 'RBI_batter',
 'bat_OBP',
 'ISO_batter',
 'pitcher_BASES_VS_AB',
 'TAV_SIDE_pit',
 'def_H',
 'pitcher_PPF',
 'TB_SIDE_pit',
 'DP_batter',
 'bat_AVG',
 'bat_TAV',
 'def_GB%',
 'batter_BASES_VS_AB',
 'OBP_SIDE_pit',
 'SDTHB_BAT',
 'def_POP%',
 'pitcher_SO',
 'bat_SLG',
 'BASES_VS_AB_batter',
 'AVG_SIDE_pit',
 'SH_SIDE_pit',
 '3B_SIDE_pit',
 'H_SIDE_pit',
 'bat_ISO', 'TB_batter', 'SF_SIDE_pit', '1B_SIDE_pit',
 'R_batter', 'Rain', 'Temp', 'SO_SIDE_pit',
 'DP_SIDE_pit', 'GB%_batter', '2B_SIDE_pit', 'BB_SIDE_pit', 'POP%_SIDE_pit',
 'HBP_SIDE_pit',
 'SO_batter', 'FB%_batter', 'CFIP_SIDE_pit',
 'pitcher_ERA', 'POP%_batter', 'LD%_SIDE_pit',
 'GB%_SIDE_pit',
 'LD%_batter', 'HR_SIDE_pit', 'bat_RBI', 'FB%_SIDE_pit',
 'bat_SO', 'bat_FB%', 'bat_DP', 'Humidity', 'Expected_Runs',
 'bat_GB%', 'bat_POP%', 'bat_LD%']

g_df_away_cols = ['Date_Team', 'date', 'team_away', 'team_home', 'pitcher_home', 'expected_runs_away', 'actual_runs_away', 
                                       'temp', 'humidity', 'rain', 'league']
g_df_away_titles = ['Date_Team','Date', 'Team_Bat', 'Stadium', 'Team_Pitch', 'Expected_Runs', 'Runs', 'Temp', 
                                        'Humidity', 'Rain', 'League']


TEAM_ORIGINAL = {
'ERIK KRATZ' : 'NYA',
'MELKY CABRERA' : 'KCA',
"PETER O'BRIEN" : 'LAN',
'CHRIS HERRMANN' : 'ARI',
'MARK REYNOLDS' : 'COL',
'MATT HOLLIDAY' : 'NYA',
'RYAN LAVARNWAY' : 'OAK',
'VIDAL NUNO' : 'BAL',
'TIM FEDEROWICZ' : 'SFN',
'BRANDON PHILLIPS' : 'ANA',
'DECK MCGUIRE' : 'CIN',
'PETE KOZMA' : 'TEX',
'TREVOR PLOUFFE' : 'TEX',
'JUSTIN MILLER' : 'COL',
'DUSTIN GARNEAU' : 'OAK',
'BRANDON BARNES' : 'COL',
'WILMER FONT' : 'OAK',
'ADAM ROSALES' : 'PHI',
'PATRICK KIVLEHAN' : 'CIN',
'DARNELL SWEENEY' : 'LAN',
'MATT SKOLE' : 'WAS',
'ALEX COLOME' : 'TBA',
'ALLEN WEBSTER' : 'PIT',
'ANTHONY BASS' : 'TEX',
'BOBBY WAHL' : 'OAK',
'ERIK GOEDDEL' : 'TEX',
'EVAN MARSHALL' : 'SEA',
'JOSE VALDEZ' : 'HOU',
'KEONE KELA' : 'TEX',
'LOUIS COLEMAN' : 'LAN',
'MATT BELISLE' : 'CLE',
'MIKE ZAGURSKI' : 'NYA',
'OLIVER PEREZ' : 'WAS',
'PAT VENDITTE' : 'SEA',
'PRESTON GUILMET' : 'MIL',
'ROBERTO OSUNA' : 'TOR',
'RYAN BRASIER' : 'OAK',
'SCOTT COPELAND' : 'TOR',
'TAYLOR COLE' : 'TOR',
'TIM COLLINS' : 'KCA',
'TONY RENDA' : 'CIN',
'TY BUTTREY' : 'BOS',
'TYLER KINLEY' : 'MIN',
'WILLIAM CUEVAS' : 'DET',
'WILLIAMS JEREZ' : 'BOS',
'XAVIER CEDENO' : 'TBA',
'ZAC ROSSCUP' : 'COL',
'TERRANCE GORE' : 'KCA',
'JAKE PETRICKA' : 'CHA',
'DREW RUCINSKI' : 'MIN',
'EDWIN JACKSON' : 'WAS',
'MICHAEL REED' : 'MIL',
'NEIL RAMIREZ' : 'NYN',
'CLAY BUCHHOLZ' : 'PHI',
'NICK FRANKLIN' : 'ANA',
'ROCKY GALE' : 'SDN',
'CASEY KELLY' : 'ATL',
'ADAM MOORE' : 'CLE',
'JACK REINHEIMER' : 'ARI',
'JALEN BEEKS' : 'BOS',
'TOMMY MILONE' : 'NYN',
'BOBBY WILSON' : 'TBA',
'DAN BUTLER' : 'WAS',
'MASON WILLIAMS' : 'NYA',
'JARROD SALTALAMACCHIA' : 'TOR',
"CHASE D'ARNAUD" : 'SDN',
'CORBAN JOSEPH' : 'NYA',
'TY KELLY' : 'PHI',
'RAFAEL ORTEGA' : 'ANA',
'MATT DEN DEKKER' : 'DET',
'GIOVANNY URSHELA' : 'CLE',
'TONY CRUZ' : 'KCA'}

TRADED_PLAYERS = {'Chris Archer' : ['2018-07-31', 'TB', 'PIT'],
                  'Tyler Glasnow' : ['2018-07-31', 'PIT', 'TB'],
                  'Nathan Eovaldi' : ['2018-07-25', 'TB', 'BOS'],
                  'J.A. Happ' : ['2018-07-31', 'TOR', 'NYY'],
                  'Tyson Ross' : ['2018-08-05', 'SD', 'STL'],
                  'Lance Lynn' : ['2018-07-30', 'MIN', 'NYY'],
                  'Cole Hamels' : ['2018-06-27', 'TEX', 'CHC']}

PITCHERS_SIDE = [
 'NAME',
 'HAND_pit',
 'G_SIDE_pit',
 'PA_SIDE_pit',
 'AB_SIDE_pit',
 'H_SIDE_pit',
 '1B_SIDE_pit',
 '2B_SIDE_pit',
 '3B_SIDE_pit',
 'HR_SIDE_pit',
 'TB_SIDE_pit',
 'SO_SIDE_pit',
 'BB_SIDE_pit',
 'HBP_SIDE_pit',
 'SF_SIDE_pit',
 'SH_SIDE_pit',
 'DP_SIDE_pit',
 'FB%_SIDE_pit',
 'GB%_SIDE_pit',
 'LD%_SIDE_pit',
 'POP%_SIDE_pit',
 'ISO_SIDE_pit',
 'AVG_SIDE_pit',
 'OBP_SIDE_pit',
 'SLG_SIDE_pit',
 'TAV_SIDE_pit',
 'BASES_VS_AB_pit']

'''
'CHRISTIAN BERGMAN':
'MIKE SOROKA': 
'CLAY BUCHHOLZ':
'ARIEL JURADO':
'P.J. CONLON':
'SAM GAVIGLIO':}'''

'''
for k,v in team_change.items():
    print("'" + k + "'" + ' : ' + "'" + v + "'" + ',')


for k,v in team_orig.items():
    print("'" + k + "'" + ' : ' + "'" + v + "'" + ',')
'''

BATTER_HAND_UNKNOWN = [
'TANNER ANDERSON',
 'MATT HALL',
 'JUAN SOTO',
 'HAROLD CASTRO',
 'YOAN LOPEZ',
 'JOHN BARBATO',
 'PATRICK WISDOM',
 'JEFF BRIGHAM',
 'STEVEN BARON',
 'ENYEL DE LOS SANTOS',
 'MATTHEW FESTA',
 'DANIEL PONCEDELEON',
 'CALEB FERGUSON',
 'JUNG-HO KANG',
 'MIKE TAUCHMAN',
 'GARRETT HAMPSON',
 'CHRISTIN STEWART',
 'ABIATAL AVELINO',
 'SHERMAN JOHNSON',
 'JUSTIN HANCOCK',
 'CHANCE ADAMS',
 'KEVIN KACZMARSKI',
 'DERECK RODRIGUEZ',
 'MURPHY SMITH',
 'PABLO REYES',
 'WES PARSONS',
 'STEPHEN WILKERSON',
 'ANDREW VELAZQUEZ',
 'BRETT KENNEDY',
 'CURTIS CASALI',
 'SAMUEL GAVIGLIO',
 'ALEX MCRAE',
 'CHRIS SHAW',
 'NICK CIUFFO',
 'FRANMIL REYES',
 'CHAD SOBOTKA',
 'JAKE NEWBERRY',
 'DUSTIN PETERSON',
 'DAVID FLETCHER',
 'JASON ADAM',
 'TOUKI TOUSSAINT',
 'SEAN REID-FOLEY',
 'ISAAC GALLOWAY',
 'STEVEN DUGGAR',
 'KEVIN NEWMAN',
 'JOSE FERNANDEZ',
 'JERRY VASTO',
 'AUSTIN DAVIS',
 'JOSE BRICENO',
 'BEAU TAYLOR',
 'NICK MARTINI',
 'JEREMY BLEICH',
 'C.D. PELHAM',
 'KEVIN KRAMER',
 'TAYLOR WARD',
 'D.J. STEWART',
 'KRIS NEGRON',
 'TIMOTHY PETERSON',
 'AUSTIN DEAN',
 'ERIC HANHOLD',
 'MITCH WALDING',
 'EVAN PHILLIPS',
 'DAKOTA HUDSON',
 'JOSE ADOLIS GARCIA',
 'KOLBY ALLARD',
 'JONATHON BERTI',
 'JOE HUDSON',
 'BRANDON DIXON',
 'DANIEL ZAMORA',
 'NATHAN ORF',
 'D.J. JOHNSON',
 'MICHAEL PEREZ',
 'JOHN ANDREOLI',
 'SHANE BIEBER',
 'WILLIANS ASTUDILLO',
 'DREW SMITH',
 'JEFFREY SPRINGS',
 'DUANE UNDERWOOD',
 'JAMES NORWOOD',
 "RYAN O'HEARN",
 'LUIS URIAS',
 'JACOB NIX',
 'PHIL ERVIN',
 'P.J. CONLON',
 'TREY WINGENTER',
 'CEDRIC MULLINS',
 'FRANCISCO ARCIA',
 'JOSHUA RIDDLE',
 'KYLE MCGOWIN',
 'CORBIN BURNES',
 'BRANDON LOWE',
 'ROBERT STOCK',
 'RYAN MEISINGER',
 'GABRIEL GUERRERO',
 'JEFF MCNEIL',
 'MATT STRAHM',
 'AUSTEN WILLIAMS',
 'ADALBERTO MONDESI',
 'KYLE WRIGHT',
 'ERIC YOUNG',
 'JOSEPH KREHBIEL',
 'JONATHAN DAVIS',
 'MYLES STRAW',
 'RONNY RODRIGUEZ',
 'BEN MEYER',
 'MIKE SOROKA',
 'KYLE TUCKER',
 'BRYSE WILSON']

 
PITCHER_HAND = {
'Jake Arrieta' : 'R',
'Mike Soroka' : 'R',
'P.J. Conlon' : 'L'
}

