name: jupyter_notebooks
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - cycler=0.10.0
  - freetype=2.9.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.5
  - joblib=0.14.1
  - jpeg=9b
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libpng=1.6.37
  - littleutils=0.2.2
  - matplotlib=3.1.1
  - mkl=2019.5
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - mpmath=1.1.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - openssl=1.1.1d
  - outdated=0.2.0
  - pandas=0.25.1
  - pandas-flavor=0.2.0
  - patsy=0.5.1
  - pingouin=0.3.2
  - pip=20.0.2
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.9.7
  - requests=2.22.0
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - seaborn=0.10.0
  - setuptools=45.1.0
  - sip=4.19.13
  - six=1.14.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tornado=6.0.3
  - urllib3=1.25.7
  - vc=14.1
  - vs2015_runtime=15.5.2
  - wheel=0.34.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xarray=0.14.1
  - zlib=1.2.11
